services:
  errand_runner:
    image: josiahdc/errand_runner:0.2
    build:
      context: errand_runner
    networks:
      - ratatosk
    env_file:
      - ratatosk.env

  echo_runner:
    image: josiahdc/echo_runner:0.2
    build:
      context: echo_runner
    networks:
      - ratatosk
    env_file:
      - ratatosk.env

networks:
  ratatosk:
    driver: bridge