services:
  rabbit:
    image: rabbitmq:3
    ports:
      - "39393:5672"
    volumes:
      - ./rabbit_setup.sh:/atelier/rabbit_setup.sh
    command: >
      sh -c "/atelier/rabbit_setup.sh &
      rabbitmq-server"
    env_file: "../ratatosk.env"
